language: c
compiler:
- gcc
env:
  global:
    secure: ZzXSXA8FHjCgVMpHTyCw7elrRa9LTHkMWRZyt2DNxcNra8URZuhoHUoa+D/bxIEOMp0vOYliHg/Umn6hWDV9wi2CRWVZdcYLhMvHRdDfM+uW7fS0R8/cFkfoGsit88IfYC865Xs/IsWhdMhXG9DSiRaaOmQI9nSnekrAFmQ3S7yht5Nk77+X7O+hVdXAMjhi7CVwQhCY+H5nRa7qSd+7SxCmShhAh4dosPmNVphQPJ1BE18jad0R3YxHjn3tpiN1z2NrWJQt7Ce+hdu9fR7P+vNXIcbFxjn2bC6nbnUY6/fKshOw9TD2qNhQlk6H37oanbIlWYGmdxpeqlyhCP0HSixtfYojkvEQ90+sp6tIm329acXXih/WHG2opgMAfFsn79ynzTl1BIFIIDMYkhOBaR/ziDuy/Ck7QUSnl/wioWqbCX8ndZ+dqUzUtT2LqmN6o1RuDtDcfCV5NvxQ322zm9OBrIBbSvXj1IMB2muCI4mmGips3kud359HCL93PeuaBnqaBmv3lbwatdEgiQArwxuFXwD9ibdFA71GmJEOohIGyGyXV5y9V5dWNQcgAGT1QgWCjeQWiA/aMV496CHDcIby5sWJqFnhfcpamsbV5JGrVKxsgliOQKt07gcFhdFI+BeEp6B79LfaVUJsYUP/vddNFK7wLReipBIwl6cJ2vg=
before_install:
- sudo pip install codecov
install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov
script:
- mkdir build
- cd build
- cmake ..
- make
- make test
- make coverage
after_success:
- codecov
