language: c
compiler:
    - gcc
env:
  global:
    secure: gVS8YeO4IyL60A0olrIsvIAAc8LGdqKi2TeNR4AM4MdcOGKMDiHUFehv0OLzSpFVw+TPgrYR8SD9wc73O761HR6vbZuKsh0IzlmXp07dBvFJDSa5gnX9lULW1XylJHQM+vevuvuA6T5xDK/VWH0vItw9CRg4XMVEvuWTYVjaFeEjk1nj3fpCu3Kd85TZNnDcz08lqUpbkVN6jnmWw7gtfHFXKyU+itA+F9orgXkvwjemdSMvsk3rl7n+Wp5FZ76R0HN2jSr7esoAt2zXUAeQRJ38G7jcVlfqXeeA9ZWUPCfuoa95N6o/4vGriaLST29UyMMn57cOB03Pw28gyStP+vsQBGzV7fDGCt19SI9nSb93wWrJqSFeCKeMwNUYORDC5v/s/b5F2uHOOhWWqQHaqvFHTXAmI7bAff8Faht3OOOy6KiFSEjEkvhNjP6TaCnRj5pY1awE+EvDP7GrqyxTG/zPA/8PfoalsiYrlfcaRBjeqCulIELUoIXp+XRKOg/GDXHYu+43NGEicYkTQI/ETkM+e6wpoAXhyNBBSFlz5OsI2JywV0KgyuK3lMpO4B/1BKKSAWJxCqnKg1xcRNXj2ceISsqsNdmk9baiEft3FzCx56j5pU9rTBknD5CSCLaV4P37G07o2/Ycad8wG+ZLkJjN/swoGy0V4O5lTxhqfl0=
#   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
#   #   via the "travis encrypt" command using the project repo's public key
#   - secure: ""

addons:
#  coverity_scan:
#    project:
#      name: "Comcast/parodus"
#      description: "The WebPA client."
#    notification_email: weston_schmidt@alumni.purdue.edu
#    build_command_prepend: "mkdir coverity_build && cd coverity_build && cmake .."
#    build_command:   "make"
#    branch_pattern: master

before_install:
    - sudo pip install codecov

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
    - make coverage

after_success:
    - codecov
