language: c
compiler:
- gcc
before_install:
- sudo pip install codecov
install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov
script:
- mkdir build
- cd build
- cmake ..
- make
- make test
- make coverage
after_success:
- codecov
env:
  global:
  - secure: JSXFxhhczQs9XLqluGacv7t1RXxaGcIXKuNY60etcTT1pvH3RwxRqbm6KhN2T5ScK1P0Onj0+pL4v5HHYiMhZWUXFyLBzD8nWQYfyOljpY438I1BvZs3osAfeXK1qXOXWfe0J48JR4FYXioNc5supGRavCojgv2MtTv87+jkrQORSdGT/qu3XnH1iEZsyZWn0RiyVe+NUylxdII4bUfm4Gj6MmcsH07m/dCF6Du19dHbeVhxb4jdpqzerz/H+Xvy29q2GyjxoZUMR8OYfKgHKEyvFMLvw7lq47IQM3sSBdI9AxsBPziLnp51VcZ+QxGNx6z70E2CzEi8m421VGyTapJZJmtxg4TrcJhqlblSGfUbM4R5A152xJImA02t2vsuNuFxEN2HiOUleO8g8mrSqyslHP5/XqIeu+3YIIAGzKtmf8/Qn9N3O4FOI6HTtfgdLITMRVM7rh0PkK+jPyfYPxOkOlAhVdrTPH8x89ELOPJQUVWOQL4BGDTQuLKHTazGp04yg9cuXaAhgRS1OkuXv2hK2od1/wXpcN3ikmPY7UtpmYUZW9EFMWfbtrUlY6zZzLILm6CtDkdU2U5DCM5fjRyVM/6IHSF5Q+cVFTp1d6Gnb9U3DI69j612K5hTFh8ZC6eCJXVVHHM2FY1BJiG3nJFM3EWXIhK9d47XBkw8j/o=
  - secure: Y6yH5T4NmV00fwFgHUr+sBC14wCoTEtGBseOB7pwjgIXR8j1cSg7z9jfNiiWI9ccLu3MdNeKl/UbtMAQ++RpSNfC0yYHErgjk1k+DdhEszawr/PMyeSShmEu47EaGHxmbHT3m+4fgOKfzg0eztJfzM3YD3El+sYtaQcxTaPHGqGMTP5Gp7bZM/sUSTGTqpI+8E1oM/QpfzM7zjjNkXWiqx9DxDyXOX1Gimjpp31+L9caKTAofHnwKlDqx1nGIT3SAzvfIZtBEid1XBcxdhcQ2Uj612FgJ56afQroOBoO7bxqeKEesfV9g+SH27DXKEP581BNK1Ai/1VbhUUfxwUY936903WEjGzn/HYzd72WtbVlZinnBnqSjm2FUytXkfQxRYl7KPNZOuO32C7lJ+Lofeg8Y+nbi2XEg7pspC1rdZJY8KB8FRN1ApucMTKWJt+K9b9SZZ7e3YnsZeQJsKGhao6JUzqKVnk0UdhbeJMGhVdhZUZmHjqHmoAO+XOzE+Q+l9/PVwVWwnG0avvFY7Lp6a8o2woTlTQOp3XY5NcPQDiB6tkUYQgf8Qjue4GQSihqkdAEvJOKCd8heC5TGOLMdVNxAPc55cOl8V7ncprfJS6tbqaLa/xpQ2mLeIKaUxLnokZfFZw2rLbdRBCoFqalVedSYObTTnh9TmmrlVx0nYs=
